If you look at the columns when importing asset prices, you get a vector in $\mathbb{R}^n$. When you calculate returns from time $t_k \to t_{k+1}$, you lose one row of data(from the beginning). This means each asset now has a vector in $\mathbb{R}^{n-1}$.  the data changes its matrix dimension from the price matrix $\mathbf{M}_{m \times n}$ to the return matrix $\mathbf{M}_{(m-1) \times n}$ (for example, from $\mathbf{M}_{43 \times 7}$ to $\mathbf{M}_{42 \times 7}$).

In [3]:
import pandas as pd

def return_matrix(prices: pd.DataFrame) -> pd.DataFrame:
    
    returns = prices.pct_change().dropna()

    return returns

prices = pd.read_csv("prices.csv")
prices = prices.drop(columns=["Date"], errors="ignore")
return_matrix(prices)

        AAPL      AMZN     GOOGL      META      MSFT      NVDA      TSLA
1  -0.010867 -0.020929 -0.038376  0.007060 -0.004446 -0.000230  0.005833
2  -0.008724 -0.018327 -0.000756 -0.033833 -0.022588  0.030299 -0.015925
3   0.009959 -0.008044  0.008209  0.027848  0.009037  0.005400  0.038014
4   0.002195 -0.009354 -0.001328 -0.008605 -0.002979 -0.000621  0.006795
5  -0.001111 -0.005102 -0.005493 -0.035399 -0.030379 -0.000666 -0.008677
6   0.014529 -0.007118  0.000581 -0.044466  0.002665 -0.023421 -0.007162
7   0.021933  0.024629  0.001511  0.004341  0.005564 -0.009921  0.042301
8  -0.017454 -0.021554 -0.011749 -0.000366 -0.004655 -0.003263 -0.017060
9  -0.006264 -0.005690  0.012182  0.007457  0.004344 -0.009822  0.051372
10  0.003200  0.013301  0.009396  0.016585  0.008422 -0.029061 -0.038334
11 -0.001418 -0.003854 -0.003160  0.019731  0.009029  0.021921  0.003725
12  0.011455 -0.002988 -0.014296  0.010683  0.009477 -0.015912 -0.012648
13  0.003605 -0.015445 -0.003947 -0.008748  0.017507  0.087380  0.025996
14  0.016276  0.039686  0.017437  0.012117  0.016770 -0.045750 -0.017080
15 -0.008915 -0.024997 -0.020889 -0.009827 -0.012151  0.014847  0.055054
16  0.026132 -0.018670 -0.012760  0.010833 -0.012360 -0.015128 -0.032233
17 -0.000523  0.000235  0.006268  0.024735 -0.008383  0.032055  0.002584
18  0.010001  0.015374  0.015899  0.030075  0.026770  0.018003  0.054228
19 -0.025106 -0.001506 -0.011103  0.009973 -0.020427  0.008361 -0.059224
20 -0.011720 -0.005957 -0.000295 -0.005334 -0.011507 -0.020099  0.039765
21 -0.002783 -0.017784 -0.022786  0.065544 -0.004656 -0.009126 -0.000951
22  0.035612 -0.002021  0.005898 -0.014242  0.001607 -0.022648 -0.011555
23  0.017454  0.019413  0.017739  0.005664  0.006478 -0.000321  0.005171
24  0.002438 -0.012618  0.032171  0.027113  0.019732 -0.033579 -0.017705
25 -0.005224 -0.020194 -0.012622  0.006971 -0.016403  0.005736 -0.006658
26  0.003229 -0.009903 -0.006116  0.004580 -0.013719  0.008154  0.004207
27  0.013808  0.021264  0.013008  0.013367  0.015195  0.025432  0.022677
28 -0.002582  0.010032  0.006363 -0.024270 -0.007976  0.013358 -0.005270
29  0.008479  0.018683  0.015535  0.114285  0.015857  0.022990  0.030280
30  0.002271 -0.013426 -0.010733 -0.006273 -0.007197  0.006553  0.009592
31 -0.008035 -0.022394 -0.037960  0.010182  0.005201 -0.014681  0.003220
32 -0.003264  0.000441  0.013409  0.045007 -0.005314 -0.004124 -0.005735
33  0.015331  0.001163  0.004557 -0.033347  0.036632  0.002182 -0.015426
34 -0.007828 -0.014099 -0.003402 -0.047947 -0.013465  0.016839 -0.039397
35 -0.026596  0.002113 -0.005339  0.032377 -0.000511 -0.007210 -0.012897
36  0.010990  0.010054  0.009269 -0.018422  0.007741  0.005149  0.005583
37 -0.008108 -0.003693 -0.016973  0.001034 -0.000195  0.010859 -0.001973
38  0.010202  0.013254  0.015551  0.002962  0.009224  0.013385  0.046539
39 -0.002397 -0.000477  0.008646  0.018981  0.014782  0.021158  0.021965
40  0.002223  0.019451  0.003492 -0.004071  0.007845  0.001423  0.005149
41  0.009112  0.014164  0.008111 -0.023779  0.000869 -0.007398 -0.007539
42  0.011139 -0.022545 -0.006305 -0.000582 -0.013497 -0.029435 -0.007438

In [4]:
Cov = prices.cov()
Cov

,AAPL,AMZN,GOOGL,META,MSFT,NVDA,TSLA
AAPL,149.452734,-62.480473,7.583289,767.978783,87.092272,38.326082,139.138868
AMZN,-62.480473,49.461610,13.291996,-342.015543,-19.496629,-13.825248,-59.926914
GOOGL,7.583289,13.291996,28.795001,60.879702,15.050993,1.807060,-2.253739
META,767.978783,-342.015543,60.879702,5407.114660,585.711117,329.373404,724.288742
MSFT,87.092272,-19.496629,15.050993,585.711117,160.674287,63.585855,89.118418
NVDA,38.326082,-13.825248,1.807060,329.373404,63.585855,57.960089,52.985898
TSLA,139.138868,-59.926914,-2.253739,724.288742,89.118418,52.985898,209.051502

In [5]:
import numpy as np
Cov = Cov.to_numpy()
eigenvalues, P = np.linalg.eig(Cov)
D = np.diag(eigenvalues).real

In [6]:
print("Diagonal matrix (D):")
display(pd.DataFrame(D))

Diagonal matrix (D):

,0,1,2,3,4,5,6
0,5725.369117,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000
1,0.000000,128.92481,0.000000,0.000000,0.00000,0.000000,0.000000
2,0.000000,0.00000,112.295283,0.000000,0.00000,0.000000,0.000000
3,0.000000,0.00000,0.000000,6.595513,0.00000,0.000000,0.000000
4,0.000000,0.00000,0.000000,0.000000,15.96814,0.000000,0.000000
5,0.000000,0.00000,0.000000,0.000000,0.00000,39.081213,0.000000
6,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,34.275805

In [7]:
Corr = prices.corr()
Corr = Corr.to_numpy()
eigenvalues_p, P = np.linalg.eig(Corr)
D = np.diag(eigenvalues_p).real
print("Diagonal matrix (D):")
display(pd.DataFrame(D))

Diagonal matrix (D):

          0         1         2         3         4         5         6
0  3.916659  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
1  0.000000  1.382462  0.000000  0.000000  0.000000  0.000000  0.000000
2  0.000000  0.000000  0.810075  0.000000  0.000000  0.000000  0.000000
3  0.000000  0.000000  0.000000  0.083373  0.000000  0.000000  0.000000
4  0.000000  0.000000  0.000000  0.000000  0.121931  0.000000  0.000000
5  0.000000  0.000000  0.000000  0.000000  0.000000  0.321884  0.000000
6  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.363616

In [12]:
dist = np.sqrt(2 * (1 - Corr))
display(pd.DataFrame(dist))
eigenvalues_p, dist = np.linalg.eig(dist)

          0         1         2         3         4         5         6
0  0.000000  1.858335  1.329965  0.539800  0.935924  1.084627  0.652422
1  1.858335  0.000000  1.138238  1.822825  1.561219  1.586323  1.782882
2  1.329965  1.138238  0.000000  1.300548  1.247978  1.382582  1.434607
3  0.539800  1.822825  1.300548  0.000000  0.862105  0.907351  0.798444
4  0.935924  1.561219  1.247978  0.862105  0.000000  0.825948  1.013648
5  1.084627  1.586323  1.382582  0.907351  0.825948  0.000000  1.018470
6  0.652422  1.782882  1.434607  0.798444  1.013648  1.018470  0.000000

In [13]:
prices = pd.read_csv("hourly_prices.csv")
prices = prices.drop(columns=["Date"], errors="ignore")
return_matrix(prices)

         AAPL      AMZN     GOOGL      META      MSFT      NVDA      TSLA
1   -0.001048  0.007995 -0.006906 -0.007091 -0.005733 -0.004311 -0.004553
2   -0.003355 -0.005788 -0.000268 -0.003320  0.000685 -0.005058  0.001364
3    0.003077 -0.002174  0.000903 -0.004637 -0.002981  0.000724 -0.004599
4    0.000799 -0.004088 -0.001043 -0.002876 -0.006516  0.000192 -0.001428
5    0.001679  0.000778  0.002484 -0.000822 -0.001317  0.002786  0.003957
..        ...       ...       ...       ...       ...       ...       ...
302  0.005211  0.004732 -0.004311 -0.000936  0.003727 -0.003815 -0.015689
303 -0.000538  0.004556  0.009087  0.004675  0.001986 -0.001501  0.004329
304  0.001225 -0.004363 -0.006606  0.000366 -0.001440  0.002114 -0.000862
305  0.003428  0.003133 -0.000952 -0.008717  0.001236 -0.000921  0.002928
306  0.006994  0.001763 -0.000782  0.001657  0.002488  0.000225  0.000339

[306 rows x 7 columns]

In [ ]:
Cov = prices.cov()
eigenvalues, P = np.linalg.eig(Cov)
D = np.diag(eigenvalues).real
display(pd.DataFrame(Cov))
#display(pd.DataFrame(D))

,AAPL,AMZN,GOOGL,META,MSFT,NVDA,TSLA
AAPL,149.915374,-60.368902,10.701199,754.271759,86.981421,36.204123,141.306658
AMZN,-60.368902,47.526912,13.925449,-317.571438,-14.493513,-11.265777,-61.702168
GOOGL,10.701199,13.925449,31.631445,76.611176,18.844230,2.805454,-0.044506
META,754.271759,-317.571438,76.611176,5259.377619,596.695461,314.443066,744.205133
MSFT,86.981421,-14.493513,18.844230,596.695461,186.305826,67.944174,93.611017
NVDA,36.204123,-11.265777,2.805454,314.443066,67.944174,56.647006,46.108604
TSLA,141.306658,-61.702168,-0.044506,744.205133,93.611017,46.108604,224.698659

,0,1,2,3,4,5,6
0,5586.612335,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,135.771838,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,133.017137,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,6.097723,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,19.191476,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,40.541913,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,34.870419

In [26]:
X = prices
n = len(X)  
X_mean = np.mean(X, axis=0)
X_c = X - X_mean
Cov = (X_c.T @ X_c) / (n - 1)
display(pd.DataFrame(Cov))

,AAPL,AMZN,GOOGL,META,MSFT,NVDA,TSLA
AAPL,149.915374,-60.368902,10.701199,754.271759,86.981421,36.204123,141.306658
AMZN,-60.368902,47.526912,13.925449,-317.571438,-14.493513,-11.265777,-61.702168
GOOGL,10.701199,13.925449,31.631445,76.611176,18.844230,2.805454,-0.044506
META,754.271759,-317.571438,76.611176,5259.377619,596.695461,314.443066,744.205133
MSFT,86.981421,-14.493513,18.844230,596.695461,186.305826,67.944174,93.611017
NVDA,36.204123,-11.265777,2.805454,314.443066,67.944174,56.647006,46.108604
TSLA,141.306658,-61.702168,-0.044506,744.205133,93.611017,46.108604,224.698659


$$
\boldsymbol{\Sigma}
=\frac{1}{T-1}\mathbf{X}_c^\top\mathbf{X}_c
$$

$$
=\frac{1}{T-1}
\begin{bmatrix}
\sum_{t=1}^{T}x_{t,1}^{2}
& \sum_{t=1}^{T}x_{t,1}x_{t,2}
& \cdots
& \sum_{t=1}^{T}x_{t,1}x_{t,n}\\
\sum_{t=1}^{T}x_{t,2}x_{t,1}
& \sum_{t=1}^{T}x_{t,2}^{2}
& \cdots
& \sum_{t=1}^{T}x_{t,2}x_{t,n}\\
\vdots & \vdots & \ddots & \vdots\\
\sum_{t=1}^{T}x_{t,n}x_{t,1}
& \sum_{t=1}^{T}x_{t,n}x_{t,2}
& \cdots
& \sum_{t=1}^{T}x_{t,n}^{2}
\end{bmatrix}
$$

$$
D_{\sigma}=
\begin{bmatrix}
\sigma_1 & 0 & \cdots & 0\\
0 & \sigma_2 & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & \sigma_n
\end{bmatrix}
$$

$$
\mathbf{R}
=D_{\sigma}^{-1}\boldsymbol{\Sigma}D_{\sigma}^{-1}
$$

$$
\mathbf{R}=
\begin{bmatrix}
\frac{1}{\sigma_1} & 0 & \cdots & 0\\
0 & \frac{1}{\sigma_2} & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & \frac{1}{\sigma_n}
\end{bmatrix}
\boldsymbol{\Sigma}
\begin{bmatrix}
\frac{1}{\sigma_1} & 0 & \cdots & 0\\
0 & \frac{1}{\sigma_2} & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & \frac{1}{\sigma_n}
\end{bmatrix}
$$